/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop2_tugas3;

import java.awt.Color;
import java.awt.Font;
import java.awt.Panel;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MohamadEsa
 */
public class graphics1_form extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public graphics1_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelArea = new javax.swing.JPanel();
        labelAJa = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTampil = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cb_warna = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_font = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_Size = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_Style = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menampilkan Grapichs Part 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAJa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAJa.setText("Hasil Yang Muncul");
        panelArea.add(labelAJa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        txtTampil.setEditable(false);
        txtTampil.setColumns(20);
        txtTampil.setRows(5);
        txtTampil.setText("Ini adalah contoh teks yang muncul");
        jScrollPane2.setViewportView(txtTampil);

        panelArea.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 160));

        jLabel2.setText("Ubah Warna");

        cb_warna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Putih", "Merah", "Ungu", "Kuning", "Hijau" }));
        cb_warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_warnaActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Font");

        cb_font.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Arial", "Arial Black", "Consolas", "Lucida Calligraphy", "Script MT Bold", "Times New Roman", " " }));
        cb_font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fontActionPerformed(evt);
            }
        });

        jLabel6.setText("Ukuran Font");

        cb_Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "10", "12", "14", "16", "18", "24", "36" }));
        cb_Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_SizeActionPerformed(evt);
            }
        });

        jLabel7.setText("Gaya Font");

        cb_Style.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Tipis", "Tebal", "Miring" }));
        cb_Style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_StyleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_font, 0, 175, Short.MAX_VALUE)
                                .addComponent(cb_warna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cb_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(cb_Style, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(panelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_warna, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_font, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_Style, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelArea, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_warnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_warnaActionPerformed
        if(cb_warna.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pilih Warna");
        } else if (cb_warna.getSelectedIndex() == 1){
            panelArea.setBackground(new Color(255,255,255));
            labelAJa.setForeground(Color.BLACK);
        } else if (cb_warna.getSelectedIndex() == 2){
            panelArea.setBackground(new Color(255,0,0));
            labelAJa.setForeground(Color.WHITE);
        } else if (cb_warna.getSelectedIndex() == 3){
            panelArea.setBackground(new Color(255,51,255));
            labelAJa.setForeground(Color.WHITE);
        } else if (cb_warna.getSelectedIndex() == 4){
            panelArea.setBackground(new Color(255,255,0));
            labelAJa.setForeground(Color.BLACK);
        } else if (cb_warna.getSelectedIndex() == 5){
            panelArea.setBackground(new Color(51,255,51));
            labelAJa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_cb_warnaActionPerformed

    private void cb_fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fontActionPerformed
        if(cb_font.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "PIlih Font");
        } else if(cb_font.getSelectedIndex() == 1){
            txtTampil.setFont(new Font("Arial", Font.PLAIN,12));
        } else if(cb_font.getSelectedIndex() == 2){
            txtTampil.setFont(new Font("Arial Black", Font.PLAIN,12));
        } else if(cb_font.getSelectedIndex() == 3){
            txtTampil.setFont(new Font("Consolas", Font.PLAIN,12));
        } else if(cb_font.getSelectedIndex() == 4){
            txtTampil.setFont(new Font("Lucida Calligraphy", Font.PLAIN,12));
        } else if(cb_font.getSelectedIndex() == 5){
            txtTampil.setFont(new Font("Script MT Bold", Font.PLAIN,12));
        } else if(cb_font.getSelectedIndex() == 6){
            txtTampil.setFont(new Font("Times New Roman", Font.PLAIN,12));
        } 
    }//GEN-LAST:event_cb_fontActionPerformed

    private void cb_SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_SizeActionPerformed
        if(cb_Size.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pilih Ukuran");
        } else if(cb_Size.getSelectedIndex() == 1){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 10));
        } else if(cb_Size.getSelectedIndex() == 2){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 12));
        } else if(cb_Size.getSelectedIndex() == 3){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 14));
        } else if(cb_Size.getSelectedIndex() == 4){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 16));
        } else if(cb_Size.getSelectedIndex() == 5){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 18));
        } else if(cb_Size.getSelectedIndex() == 6){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 24));
        } else if(cb_Size.getSelectedIndex() == 7){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), txtTampil.getFont().getStyle(), 36));
        }
    }//GEN-LAST:event_cb_SizeActionPerformed

    private void cb_StyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_StyleActionPerformed
        if(cb_Style.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Pilih Gaya Font");
        } else if(cb_Style.getSelectedIndex() == 1){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), Font.PLAIN, txtTampil.getFont().getSize()));
        } else if(cb_Style.getSelectedIndex() == 2){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), Font.BOLD, txtTampil.getFont().getSize()));
        } else if(cb_Style.getSelectedIndex() == 3){
            txtTampil.setFont(new Font(txtTampil.getFont().getName(), Font.ITALIC, txtTampil.getFont().getSize()));
        }
    }//GEN-LAST:event_cb_StyleActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Size;
    private javax.swing.JComboBox<String> cb_Style;
    private javax.swing.JComboBox<String> cb_font;
    private javax.swing.JComboBox<String> cb_warna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAJa;
    private javax.swing.JPanel panelArea;
    private javax.swing.JTextArea txtTampil;
    // End of variables declaration//GEN-END:variables
}
